### ISSUE TITLE
Very slow with shield TV pro

### ISSUE THREAD

**Issue by Coverdale1987** [libretro/geolith-libretro#4]
Hello, Many thanks for this new neo geo core.

Unfortunatly, Emulator is very slow with shield TV pro. (Approx  35fps).
Retroarc64  version:  1.18.0
OS: Android V11

But perfectly with my android tablet under android 13.

Any idea ?

**Comment by carmiker** [comment]
Looking at the specs for the Shield Pro, it shouldn't be this slow, however, this emulator was not built with speed as a priority. I do have some ways to speed it up, but before I start taking shortcuts I want to get Neo Geo CD support done, and finish the hardware research I am currently engaged in, then implement any new findings in the emulator.

I don't know much about Android or its ecosystem, it could also be slow due to something I am unaware of.
